### warranty.http – Garantías de equipos Rentool
@baseUrl = http://localhost:4000

### Consultar todas las garantías
GET {{baseUrl}}/api/warranties

### Consultar garantía por ID
GET {{baseUrl}}/api/warranties/1

### Crear garantía
POST {{baseUrl}}/api/warranties
Content-Type: application/json

{
  "equipment_id": 1,
  "contract_id": 1,
  "start_date": "2025-10-15",
  "end_date": "2025-10-20",
  "description": "Cobertura por daño eléctrico menor",
  "status": "ACTIVE"
}

### Actualizar garantía
PATCH {{baseUrl}}/api/warranties/1
Content-Type: application/json

{
  "description": "Cobertura extendida de mantenimiento preventivo"
}

### Eliminar físicamente
DELETE {{baseUrl}}/api/warranties/1

### Eliminar lógicamente
DELETE {{baseUrl}}/api/warranties/1/logic
