### GET all user-role relations
GET http://localhost:3000/api/role_user
#Authorization: Bearer {{token}}

### ASSIGN role to user
POST http://localhost:3000/api/role_user
#Authorization: Bearer {{token}}
Content-Type: application/json

{
  "userId": 2,
  "roleId": 1
}

### DELETE user-role relation
DELETE http://localhost:3000/api/role_user/2
#Authorization: Bearer {{token}}
